version: "3.7"
services:
  arangodb:
    image: arangodb/arangodb:3.7.10
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - ./data/arangodb/data:/var/lib/arangodb3
      - ./data/arangodb/apps:/var/lib/arangodb3-apps
